package com.nick.nutritiontracker.ui

import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.grid.GridCells
import androidx.compose.foundation.lazy.grid.GridItemSpan
import androidx.compose.foundation.lazy.grid.LazyVerticalGrid
import androidx.compose.foundation.lazy.grid.items
import androidx.compose.foundation.lazy.items
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Add
import androidx.compose.material.icons.filled.Close
import androidx.compose.material.icons.filled.Delete
import androidx.compose.material.icons.filled.ExpandLess
import androidx.compose.material.icons.filled.ExpandMore
import androidx.compose.material.icons.filled.Kitchen
import androidx.compose.material.icons.filled.ShoppingCart
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.scale
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import com.nick.nutritiontracker.data.ShoppingItem
import com.nick.nutritiontracker.viewmodel.NutritionViewModel

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun ShoppingListScreen(vm: NutritionViewModel) {
    val rawShoppingList = vm.shoppingList
    val household by vm.firebaseManager.household.collectAsState()
    
    var showAddItemDialog by remember { mutableStateOf(false) }
    var isArchiveExpanded by remember { mutableStateOf(false) }

    val activeItems by remember(rawShoppingList, vm.showPantryInShoppingList) { 
        derivedStateOf { 
            rawShoppingList.filter { 
                !it.isChecked && (vm.showPantryInShoppingList || !it.isPantryItem)
            } 
        } 
    }
    val checkedItems by remember(rawShoppingList) { 
        derivedStateOf { rawShoppingList.filter { it.isChecked } } 
    }

    val categoryOrder = listOf(
        "Obst", "Gemüse", "Backwaren", "Kühlregal", "Fleisch", 
        "Milchprodukte", "Protein", "Teigwaren", "Convenience", 
        "Fertiggerichte", "Tiefkühlprodukte", "Süßigkeiten", "Getränke"
    )

    val aggregatedActiveList by remember(activeItems, vm.isShoppingListAggregated) {
        derivedStateOf {
            if (vm.isShoppingListAggregated) {
                activeItems.groupBy { it.name.lowercase().trim() to it.baseUnit }
                    .flatMap { (_, items) ->
                        val weightItems = items.filter { it.weightGrams > 0 }
                        val otherItems = items.filter { it.weightGrams <= 0 }
                        
                        val results = mutableListOf<ShoppingItem>()
                        
                        if (weightItems.isNotEmpty()) {
                            val totalWeight = weightItems.sumOf { it.weightGrams }
                            val first = weightItems.first()
                            results.add(
                                ShoppingItem(
                                    id = first.id,
                                    name = first.name,
                                    amount = totalWeight,
                                    unit = first.baseUnit,
                                    isChecked = false,
                                    isAutoGenerated = weightItems.any { it.isAutoGenerated },
                                    householdId = first.householdId,
                                    sourceName = if (weightItems.size > 1) "${weightItems.size} Quellen" else first.sourceName,
                                    weightGrams = totalWeight,
                                    baseUnit = first.baseUnit,
                                    category = first.category,
                                    isPantryItem = weightItems.any { it.isPantryItem }
                                )
                            )
                        }
                        
                        if (otherItems.isNotEmpty()) {
                            otherItems.groupBy { it.unit.lowercase().trim() }
                                .forEach { (_, group) ->
                                    val first = group.first()
                                    results.add(
                                        ShoppingItem(
                                            id = first.id,
                                            name = first.name,
                                            amount = group.sumOf { it.amount },
                                            unit = first.unit,
                                            isChecked = false,
                                            isAutoGenerated = group.any { it.isAutoGenerated },
                                            householdId = first.householdId,
                                            sourceName = if (group.size > 1) "${group.size} Quellen" else first.sourceName,
                                            weightGrams = 0.0,
                                            baseUnit = first.baseUnit,
                                            category = first.category,
                                            isPantryItem = group.any { it.isPantryItem }
                                        )
                                    )
                                }
                        }
                        results
                    }
            } else {
                activeItems
            }
        }
    }

    val groupedActiveItems by remember(aggregatedActiveList, vm.isShoppingListAggregated, vm.shoppingListSortByCategory) {
        derivedStateOf {
            if (vm.shoppingListSortByCategory) {
                aggregatedActiveList.groupBy { 
                    val cat = it.category
                    if (cat.isNullOrBlank()) "Sonstiges" else cat 
                }
                    .toList()
                    .sortedBy { (cat, _) -> 
                        val idx = categoryOrder.indexOf(cat)
                        if (idx == -1) categoryOrder.size else idx
                    }.toMap()
            } else {
                aggregatedActiveList.groupBy { it.sourceName ?: "Manuell hinzugefügt" }
            }
        }
    }

    if (household == null) {
        Box(Modifier.fillMaxSize(), contentAlignment = Alignment.Center) {
            Text("Bitte erstelle einen Haushalt im Profil, um die Einkaufsliste zu nutzen.")
        }
        return
    }

    Scaffold(
        floatingActionButton = {
            FloatingActionButton(onClick = { showAddItemDialog = true }) {
                Icon(Icons.Default.Add, "Artikel hinzufügen")
            }
        }
    ) { padding ->
        Column(Modifier.padding(padding).padding(horizontal = 12.dp)) {
            if (!household?.name.isNullOrBlank()) {
                Text(
                    text = "Haushalt: ${household!!.name}", 
                    style = MaterialTheme.typography.labelSmall, 
                    color = MaterialTheme.colorScheme.outline,
                    modifier = Modifier.padding(vertical = 4.dp)
                )
            }

            LazyVerticalGrid(
                columns = GridCells.Fixed(2),
                verticalArrangement = Arrangement.spacedBy(8.dp),
                horizontalArrangement = Arrangement.spacedBy(8.dp),
                modifier = Modifier.weight(1f),
                contentPadding = PaddingValues(top = 4.dp, bottom = 80.dp)
            ) {
                groupedActiveItems.forEach { (header, items) ->
                    item(key = "header_$header", span = { GridItemSpan(2) }) {
                        Text(
                            text = header,
                            style = MaterialTheme.typography.titleSmall,
                            color = MaterialTheme.colorScheme.primary,
                            modifier = Modifier.padding(top = 12.dp, bottom = 4.dp)
                        )
                    }
                    items(items, key = { it.id }) { item ->
                        ShoppingItemTile(
                            item = item,
                            onToggle = { vm.toggleShoppingItem(item) },
                            onDelete = { 
                                if (vm.isShoppingListAggregated) {
                                    val isWeightItem = item.weightGrams > 0
                                    val related = activeItems.filter { 
                                        val nameMatch = it.name.equals(item.name, ignoreCase = true)
                                        if (isWeightItem) {
                                            nameMatch && it.weightGrams > 0 && it.baseUnit.equals(item.baseUnit, ignoreCase = true)
                                        } else {
                                            nameMatch && it.unit.equals(item.unit, ignoreCase = true)
                                        }
                                    }
                                    related.forEach { vm.deleteShoppingItem(it.id) }
                                } else {
                                    vm.deleteShoppingItem(item.id)
                                }
                            }
                        )
                    }
                }

                if (checkedItems.isNotEmpty()) {
                    item(key = "archive_header", span = { GridItemSpan(2) }) {
                        Column {
                            HorizontalDivider(Modifier.padding(vertical = 16.dp))
                            Surface(
                                onClick = { isArchiveExpanded = !isArchiveExpanded },
                                modifier = Modifier.fillMaxWidth(),
                                color = Color.Transparent
                            ) {
                                Row(
                                    verticalAlignment = Alignment.CenterVertically,
                                    horizontalArrangement = Arrangement.SpaceBetween,
                                    modifier = Modifier.padding(vertical = 8.dp)
                                ) {
                                    Text(
                                        "Zuletzt verwendet (${checkedItems.size})",
                                        style = MaterialTheme.typography.titleSmall,
                                        color = MaterialTheme.colorScheme.outline
                                    )
                                    Icon(
                                        imageVector = if (isArchiveExpanded) Icons.Default.ExpandLess else Icons.Default.ExpandMore,
                                        contentDescription = null,
                                        tint = MaterialTheme.colorScheme.outline
                                    )
                                }
                            }
                        }
                    }

                    if (isArchiveExpanded) {
                        items(checkedItems, key = { "checked_${it.id}" }, span = { GridItemSpan(2) }) { item ->
                            ShoppingItemRow(
                                item = item,
                                onToggle = { vm.toggleShoppingItem(item) },
                                onDelete = { vm.deleteShoppingItem(item.id) }
                            )
                        }
                    }
                }
            }
        }
    }

    if (showAddItemDialog) {
        AddShoppingItemDialog(
            onDismiss = { showAddItemDialog = false },
            onAdd = { name, amount, unit ->
                vm.addShoppingItem(name, amount, unit)
                showAddItemDialog = false
            }
        )
    }
}

@Composable
fun ShoppingItemTile(item: ShoppingItem, onToggle: () -> Unit, onDelete: () -> Unit) {
    Card(
        modifier = Modifier
            .fillMaxWidth()
            .height(84.dp) // Fixed height for a uniform grid
            .clickable { onToggle() },
        colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface),
        border = BorderStroke(1.dp, MaterialTheme.colorScheme.outlineVariant.copy(alpha = 0.5f))
    ) {
        Column(
            modifier = Modifier.padding(10.dp).fillMaxHeight(),
            verticalArrangement = Arrangement.SpaceBetween
        ) {
            Row(verticalAlignment = Alignment.Top) {
                Row(modifier = Modifier.weight(1f), verticalAlignment = Alignment.CenterVertically) {
                    Text(
                        text = item.name, 
                        fontWeight = FontWeight.Bold, 
                        style = MaterialTheme.typography.bodyMedium,
                        modifier = Modifier.weight(1f, fill = false),
                        maxLines = 2,
                        overflow = androidx.compose.ui.text.style.TextOverflow.Ellipsis
                    )
                    if (item.isPantryItem) {
                        Spacer(Modifier.width(4.dp))
                        Icon(
                            imageVector = Icons.Default.Kitchen, 
                            contentDescription = "Vorrat", 
                            tint = Color(0xFF2E7D32),
                            modifier = Modifier.size(14.dp)
                        )
                    }
                }
                IconButton(
                    onClick = onDelete,
                    modifier = Modifier.size(24.dp).offset(x = 4.dp, y = (-4).dp)
                ) {
                    Icon(Icons.Default.Close, null, tint = MaterialTheme.colorScheme.outline, modifier = Modifier.size(16.dp))
                }
            }
            
            if (item.amount > 0) {
                Text(
                    text = "${item.amount.roundString()} ${item.unit}", 
                    style = MaterialTheme.typography.labelSmall, 
                    color = MaterialTheme.colorScheme.primary,
                    maxLines = 1
                )
            }
        }
    }
}

@Composable
fun ShoppingItemRow(item: ShoppingItem, onToggle: () -> Unit, onDelete: () -> Unit) {
    Card(
        modifier = Modifier.fillMaxWidth().clickable { onToggle() },
        colors = if (item.isChecked) CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surfaceVariant) else CardDefaults.cardColors()
    ) {
        Row(
            Modifier.padding(12.dp),
            verticalAlignment = Alignment.CenterVertically
        ) {
            Checkbox(checked = item.isChecked, onCheckedChange = { onToggle() })
            Column(Modifier.weight(1f)) {
                Row(verticalAlignment = Alignment.CenterVertically) {
                    Text(
                        item.name, 
                        fontWeight = FontWeight.Bold, 
                        style = if (item.isChecked) MaterialTheme.typography.bodyMedium.copy(textDecoration = androidx.compose.ui.text.style.TextDecoration.LineThrough) else MaterialTheme.typography.bodyMedium,
                        modifier = Modifier.weight(1f, fill = false)
                    )
                    if (item.isPantryItem) {
                        Spacer(Modifier.width(4.dp))
                        Icon(
                            imageVector = Icons.Default.Kitchen, 
                            contentDescription = "Vorrat", 
                            tint = Color(0xFF2E7D32),
                            modifier = Modifier.size(14.dp)
                        )
                    }
                }
                if (item.amount > 0) {
                    Text("${item.amount.roundString()} ${item.unit}", style = MaterialTheme.typography.labelSmall)
                }
                if (item.isAutoGenerated) {
                    Text("Auto-generiert aus Planer", style = MaterialTheme.typography.labelSmall, color = MaterialTheme.colorScheme.primary)
                }
            }
            IconButton(onClick = onDelete) {
                Icon(Icons.Default.Delete, "Löschen", tint = Color.Red)
            }
        }
    }
}

@Composable
fun AddShoppingItemDialog(onDismiss: () -> Unit, onAdd: (String, Double, String) -> Unit) {
    var name by remember { mutableStateOf("") }
    var amount by remember { mutableStateOf("") }
    var unit by remember { mutableStateOf("g") }

    AlertDialog(
        onDismissRequest = onDismiss,
        title = { Text("Artikel hinzufügen") },
        text = {
            Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
                OutlinedTextField(value = name, onValueChange = { name = it }, label = { Text("Name") })
                Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                    OutlinedTextField(value = amount, onValueChange = { amount = it }, label = { Text("Menge") }, modifier = Modifier.weight(1f))
                    OutlinedTextField(value = unit, onValueChange = { unit = it }, label = { Text("Einheit") }, modifier = Modifier.weight(1f))
                }
            }
        },
        confirmButton = {
            Button(onClick = { onAdd(name, amount.toDoubleOrNull() ?: 0.0, unit) }) {
                Text("Hinzufügen")
            }
        },
        dismissButton = {
            TextButton(onClick = onDismiss) { Text("Abbrechen") }
        }
    )
}

private fun Double.roundString(): String = if (this % 1.0 == 0.0) "%.0f".format(this) else "%.1f".format(this)
