package com.nick.nutritiontracker.ui

import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Add
import androidx.compose.material.icons.filled.Delete
import androidx.compose.material.icons.filled.ExpandLess
import androidx.compose.material.icons.filled.ExpandMore
import androidx.compose.material.icons.filled.ShoppingCart
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.scale
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import com.nick.nutritiontracker.data.ShoppingItem
import com.nick.nutritiontracker.viewmodel.NutritionViewModel

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun ShoppingListScreen(vm: NutritionViewModel) {
    val rawShoppingList = vm.shoppingList
    val household by vm.firebaseManager.household.collectAsState()
    
    var showAddItemDialog by remember { mutableStateOf(false) }
    var isArchiveExpanded by remember { mutableStateOf(false) }

    val activeItems by remember(rawShoppingList, vm.showPantryInShoppingList) { 
        derivedStateOf { 
            rawShoppingList.filter { 
                !it.isChecked && (vm.showPantryInShoppingList || !it.isPantryItem)
            } 
        } 
    }
    val checkedItems by remember(rawShoppingList) { 
        derivedStateOf { rawShoppingList.filter { it.isChecked } } 
    }

    val aggregatedActiveList by remember(activeItems, vm.isShoppingListAggregated) {
        derivedStateOf {
            if (vm.isShoppingListAggregated) {
                activeItems.groupBy { it.name.lowercase().trim() to it.baseUnit }
                    .flatMap { (_, items) ->
                        val weightItems = items.filter { it.weightGrams > 0 }
                        val otherItems = items.filter { it.weightGrams <= 0 }
                        
                        val results = mutableListOf<ShoppingItem>()
                        
                        if (weightItems.isNotEmpty()) {
                            val totalWeight = weightItems.sumOf { it.weightGrams }
                            val first = weightItems.first()
                            results.add(
                                ShoppingItem(
                                    id = first.id,
                                    name = first.name,
                                    amount = totalWeight,
                                    unit = first.baseUnit,
                                    isChecked = false,
                                    isAutoGenerated = weightItems.any { it.isAutoGenerated },
                                    householdId = first.householdId,
                                    sourceName = if (weightItems.size > 1) "${weightItems.size} Quellen" else first.sourceName,
                                    weightGrams = totalWeight,
                                    baseUnit = first.baseUnit
                                )
                            )
                        }
                        
                        if (otherItems.isNotEmpty()) {
                            otherItems.groupBy { it.unit.lowercase().trim() }
                                .forEach { (_, group) ->
                                    val first = group.first()
                                    results.add(
                                        ShoppingItem(
                                            id = first.id,
                                            name = first.name,
                                            amount = group.sumOf { it.amount },
                                            unit = first.unit,
                                            isChecked = false,
                                            isAutoGenerated = group.any { it.isAutoGenerated },
                                            householdId = first.householdId,
                                            sourceName = if (group.size > 1) "${group.size} Quellen" else first.sourceName,
                                            weightGrams = 0.0,
                                            baseUnit = first.baseUnit
                                        )
                                    )
                                }
                        }
                        results
                    }
            } else {
                activeItems
            }
        }
    }

    val groupedActiveItems by remember(aggregatedActiveList, vm.isShoppingListAggregated) {
        derivedStateOf {
            if (!vm.isShoppingListAggregated) {
                aggregatedActiveList.groupBy { it.sourceName ?: "Manuell hinzugefügt" }
            } else {
                emptyMap()
            }
        }
    }

    if (household == null) {
        Box(Modifier.fillMaxSize(), contentAlignment = Alignment.Center) {
            Text("Bitte erstelle einen Haushalt im Profil, um die Einkaufsliste zu nutzen.")
        }
        return
    }

    Scaffold(
        floatingActionButton = {
            FloatingActionButton(onClick = { showAddItemDialog = true }) {
                Icon(Icons.Default.Add, "Artikel hinzufügen")
            }
        }
    ) { padding ->
        Column(Modifier.padding(padding).padding(horizontal = 16.dp, vertical = 8.dp)) {
            Row(
                Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.SpaceBetween,
                verticalAlignment = Alignment.CenterVertically
            ) {
                Text("Einkaufsliste", style = MaterialTheme.typography.headlineSmall, fontWeight = FontWeight.Bold)
                
                Column(horizontalAlignment = Alignment.End) {
                    Row(verticalAlignment = Alignment.CenterVertically) {
                        Text("Zusammenfassen", style = MaterialTheme.typography.labelSmall)
                        Switch(
                            checked = vm.isShoppingListAggregated,
                            onCheckedChange = { vm.isShoppingListAggregated = it },
                            modifier = Modifier.scale(0.6f)
                        )
                    }
                    Row(verticalAlignment = Alignment.CenterVertically) {
                        Text("Vorrat anzeigen", style = MaterialTheme.typography.labelSmall)
                        Switch(
                            checked = vm.showPantryInShoppingList,
                            onCheckedChange = { vm.showPantryInShoppingList = it },
                            modifier = Modifier.scale(0.6f)
                        )
                    }
                }
            }
            
            Text(household?.name ?: "", style = MaterialTheme.typography.labelMedium, color = MaterialTheme.colorScheme.outline)

            Spacer(Modifier.height(16.dp))

            LazyColumn(
                verticalArrangement = Arrangement.spacedBy(8.dp),
                contentPadding = PaddingValues(bottom = 80.dp)
            ) {
                // ACTIVE ITEMS
                if (vm.isShoppingListAggregated) {
                    items(aggregatedActiveList) { item ->
                        ShoppingItemRow(
                            item = item,
                            onToggle = { vm.toggleShoppingItem(item) },
                            onDelete = { 
                                val isWeightItem = item.weightGrams > 0
                                val related = activeItems.filter { 
                                    val nameMatch = it.name.equals(item.name, ignoreCase = true)
                                    if (isWeightItem) {
                                        nameMatch && it.weightGrams > 0 && it.baseUnit.equals(item.baseUnit, ignoreCase = true)
                                    } else {
                                        nameMatch && it.unit.equals(item.unit, ignoreCase = true)
                                    }
                                }
                                related.forEach { vm.deleteShoppingItem(it.id) }
                            }
                        )
                    }
                } else {
                    groupedActiveItems.forEach { (source, items) ->
                        item(key = source) {
                            Text(
                                text = source,
                                style = MaterialTheme.typography.titleSmall,
                                color = MaterialTheme.colorScheme.primary,
                                modifier = Modifier.padding(top = 8.dp, bottom = 4.dp)
                            )
                        }
                        items(items, key = { it.id }) { item ->
                            ShoppingItemRow(
                                item = item,
                                onToggle = { vm.toggleShoppingItem(item) },
                                onDelete = { vm.deleteShoppingItem(item.id) }
                            )
                        }
                    }
                }

                // ARCHIVE SECTION
                if (checkedItems.isNotEmpty()) {
                    item {
                        HorizontalDivider(Modifier.padding(vertical = 16.dp))
                        Surface(
                            onClick = { isArchiveExpanded = !isArchiveExpanded },
                            modifier = Modifier.fillMaxWidth(),
                            color = Color.Transparent
                        ) {
                            Row(
                                verticalAlignment = Alignment.CenterVertically,
                                horizontalArrangement = Arrangement.SpaceBetween,
                                modifier = Modifier.padding(vertical = 8.dp)
                            ) {
                                Text(
                                    "Zuletzt verwendet (${checkedItems.size})",
                                    style = MaterialTheme.typography.titleSmall,
                                    color = MaterialTheme.colorScheme.outline
                                )
                                Icon(
                                    imageVector = if (isArchiveExpanded) Icons.Default.ExpandLess else Icons.Default.ExpandMore,
                                    contentDescription = null,
                                    tint = MaterialTheme.colorScheme.outline
                                )
                            }
                        }
                    }

                    if (isArchiveExpanded) {
                        items(checkedItems, key = { "checked_${it.id}" }) { item ->
                            ShoppingItemRow(
                                item = item,
                                onToggle = { vm.toggleShoppingItem(item) },
                                onDelete = { vm.deleteShoppingItem(item.id) }
                            )
                        }
                    }
                }
            }
        }
    }

    if (showAddItemDialog) {
        AddShoppingItemDialog(
            onDismiss = { showAddItemDialog = false },
            onAdd = { name, amount, unit ->
                vm.addShoppingItem(name, amount, unit)
                showAddItemDialog = false
            }
        )
    }
}

@Composable
fun ShoppingItemRow(item: ShoppingItem, onToggle: () -> Unit, onDelete: () -> Unit) {
    Card(
        modifier = Modifier.fillMaxWidth().clickable { onToggle() },
        colors = if (item.isChecked) CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surfaceVariant) else CardDefaults.cardColors()
    ) {
        Row(
            Modifier.padding(12.dp),
            verticalAlignment = Alignment.CenterVertically
        ) {
            Checkbox(checked = item.isChecked, onCheckedChange = { onToggle() })
            Column(Modifier.weight(1f)) {
                Text(item.name, fontWeight = FontWeight.Bold, style = if (item.isChecked) MaterialTheme.typography.bodyMedium.copy(textDecoration = androidx.compose.ui.text.style.TextDecoration.LineThrough) else MaterialTheme.typography.bodyMedium)
                if (item.amount > 0) {
                    Text("${item.amount.roundString()} ${item.unit}", style = MaterialTheme.typography.labelSmall)
                }
                if (item.isAutoGenerated) {
                    Text("Auto-generiert aus Planer", style = MaterialTheme.typography.labelSmall, color = MaterialTheme.colorScheme.primary)
                }
                if (item.isPantryItem) {
                    Text("Vorratsschrank", style = MaterialTheme.typography.labelSmall, color = Color(0xFF2E7D32))
                }
            }
            IconButton(onClick = onDelete) {
                Icon(Icons.Default.Delete, "Löschen", tint = Color.Red)
            }
        }
    }
}

@Composable
fun AddShoppingItemDialog(onDismiss: () -> Unit, onAdd: (String, Double, String) -> Unit) {
    var name by remember { mutableStateOf("") }
    var amount by remember { mutableStateOf("") }
    var unit by remember { mutableStateOf("g") }

    AlertDialog(
        onDismissRequest = onDismiss,
        title = { Text("Artikel hinzufügen") },
        text = {
            Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
                OutlinedTextField(value = name, onValueChange = { name = it }, label = { Text("Name") })
                Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                    OutlinedTextField(value = amount, onValueChange = { amount = it }, label = { Text("Menge") }, modifier = Modifier.weight(1f))
                    OutlinedTextField(value = unit, onValueChange = { unit = it }, label = { Text("Einheit") }, modifier = Modifier.weight(1f))
                }
            }
        },
        confirmButton = {
            Button(onClick = { onAdd(name, amount.toDoubleOrNull() ?: 0.0, unit) }) {
                Text("Hinzufügen")
            }
        },
        dismissButton = {
            TextButton(onClick = onDismiss) { Text("Abbrechen") }
        }
    )
}

private fun Double.roundString(): String = if (this % 1.0 == 0.0) "%.0f".format(this) else "%.1f".format(this)
