package com.nick.nutritiontracker.data

import androidx.annotation.Keep
import com.google.firebase.firestore.PropertyName
import kotlinx.serialization.Serializable

@Keep
@Serializable
data class ShoppingItem(
    var id: String = "",
    var name: String = "",
    var amount: Double = 0.0,
    var unit: String = "g",
    @get:PropertyName("isChecked") @set:PropertyName("isChecked")
    var isChecked: Boolean = false,
    @get:PropertyName("isAutoGenerated") @set:PropertyName("isAutoGenerated")
    var isAutoGenerated: Boolean = false,
    var category: String? = null,
    var householdId: String = "",
    var sourceName: String? = null,
    var weightGrams: Double = 0.0,
    var baseUnit: String = "g",
    @get:PropertyName("isPantryItem") @set:PropertyName("isPantryItem")
    var isPantryItem: Boolean = false
)
