package com.nick.nutritiontracker.data

import com.google.firebase.firestore.PropertyName
import kotlinx.serialization.Serializable

@Serializable
data class ShoppingItem(
    val id: String = "",
    val name: String = "",
    val amount: Double = 0.0,
    val unit: String = "g",
    @get:PropertyName("isChecked") @set:PropertyName("isChecked")
    var isChecked: Boolean = false,
    @get:PropertyName("isAutoGenerated") @set:PropertyName("isAutoGenerated")
    var isAutoGenerated: Boolean = false,
    val category: String? = null,
    val householdId: String = "",
    val sourceName: String? = null
)
